[tools]
go = "1.24.9"
pnpm = "10.17.0"
node = "22"
lefthook = "latest"
golangci-lint = "latest"
yamlfmt = "latest"
yamllint = "latest"
biome = "latest"
act = "latest"
action-validator = "latest"
actionlint = "latest"
